# This is an example .goreleaser.yml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goarm:
      - 6
      - 7
    goarch:
      - amd64
      - arm
      - arm64
      - 386
    goos:
      - linux
      - windows
      - darwin
      - android
    ignore:
      - goos: android
        goarch: arm
      - goos: darwin
        goarch: 386
      - goos: darwin
        goarch: arm
      - goos: windows
        goarch: arm
      - goos: windows
        goarch: arm64
      - goos: android
        goarch: 386
archives:
  -
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}'
    format_overrides:
    - goos: windows
      format: zip
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    files:
      - config.yaml.example
      - LICENSE
      - README.md
      - font.ttf
      - dictionary.txt
release:
  prerelease: auto
checksum:
  name_template: 'checksums.txt'
project_name: opqbot-manager
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
gitea_urls:
  api: https://git.mcenjoy.cn/api/v1/
  download: https://git.mcenjoy.cn
  # set to true if you use a self-signed certificate
  skip_tls_verify: true
