name: goreleaser

on:
  push:
    branches:
      - 'master'
      - 'beta'
    tags:
      - 'v*'
  pull_request:

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      -
        name: Build Web
        run: |
          npm config set registry https://registry.npmjs.org
          npm install yarn -g
          yarn config set registry https://registry.yarnpkg.com
          npm install -g @quasar/cli
          chmod +x upx.sh;cd GroupManager/Web;yarn install;quasar build
      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16
      # -
      #   name: Install UPX
      #   if: success() && startsWith(github.ref, 'refs/tags/')
      #   run: |
      #     sudo apt-get install upx-ucl
      -
        name: Tests & build
        run: |
          go mod tidy
          go test -v ./...
          go build -o opqbot-manager -ldflags="-s -w" .
      - name: Log into registry
        if: success() && startsWith(github.ref, 'refs/tags/')
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      -
        name: Publish Docker
        if: success() && startsWith(github.ref, 'refs/tags/')
        env:
          docker_repo: mcenjoy
          image_name: opqbot-groupmanager
          tag: latest
        run: |
          docker version
          docker build . --file Dockerfile --tag $docker_repo/$image_name:$tag
          docker push $docker_repo/$image_name:$tag
      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: success() && startsWith(github.ref, 'refs/tags/')
        with:
          version: "v0.173.2"
          args: release --rm-dist --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
